# 2.1Data Operations 数据操作
主要学习tensor
存储以及操作数据

下载的问题

pip install numpy==1.21.5 -i https://pypi.tuna.tsinghua.edu.cn/simple

pip install pandas==1.2.4 -i https://pypi.tuna.tsinghua.edu.cn/simple


## 2.1.1入门

In [1]:
import torch

tensor其实就是一个代表任意维度的向量，只不过有一些特性而已
可以用arange函数创建一个由0到n-1的向量,没有指定的化存储在cpu

In [5]:
x=torch.arange(12)
x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
y=torch.arange(1,12,2,dtype=float)
y

tensor([ 1.,  3.,  5.,  7.,  9., 11.], dtype=torch.float64)

reshape函数可以改变tensor的形状
-1代表这个数由torch自动计算

In [7]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
x=x.reshape(3,-1)

shape可以知道tensor的形状
numel可以知道tensor的元素的总数

In [16]:
print(f"x's shape is {x.shape} ")
print(f"x's shape is {x.numel} ")

x's shape is torch.Size([3, 4]) 
x's shape is <built-in method numel of Tensor object at 0x0000017E4A84B9A0> 


arange函数得到一个等差序列

zeros函数得到全0的tensor

ones函数得到全1的

randn函数得到正态分布

In [18]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
torch.randn(3,4)

tensor([[ 0.2051,  1.2356, -0.4490, -2.0856],
        [ 0.4181,  1.7530,  0.5186,  0.0306],
        [-0.8931,  0.7663, -0.4800,  0.6271]])

### 2.1.2运算符 operator

+、-、*、/、**

exp

In [21]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [22]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

cat函数，很重要用来拼接tensor

如果 torch.cat() 处理多个张量，它们在除了拼接维度外的其他维度必须形状一致。

In [25]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(f"X is \n{X}")
print(f"Y is \n{Y}")
print(f"X 和 Y 按照行拼接\n{torch.cat([X,Y],dim=0)}")
print(f"X 和 Y 按照列拼接\n{torch.cat([X,Y],dim=1)}")

X is 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Y is 
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
X 和 Y 按照行拼接
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
X 和 Y 按照列拼接
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [26]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()

tensor(66.)

## 2.1.3 broadcasting mechanism 广播机制

在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：

通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

对生成的数组执行按元素操作。

PyTorch 遵循 NumPy 的广播规则

1. 如果两个张量的维度数量不同，则自动在较小的形状前面补 1（不会改变原张量）。

2. 如果两个张量在某个维度上的大小不同：

   - 如果其中一个为 1，则会被扩展为与另一个相同的大小。

   - 如果两者都大于 1，但不相等，则报错。

3. 当所有维度对齐后，按照较大张量的形状进行计算。

In [29]:
a = torch.tensor([[1], [2], [3]])  # shape: (3,1)
b = torch.tensor([1, 2, 3])  # shape: (3,)

print(a + b)  # 广播 b -> (1,3)，然后计算(3,1)+(1,3)->(3,3)+(3,3)


tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


In [31]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape: (2,3)
B = torch.tensor([1, 2, 3])  # shape: (3,)

print(A + B)  # 广播 B -> (1,3) ->(2,3)

A = torch.randn(2, 3, 1)  # shape: (2,3,1)
B = torch.randn(1, 3, 4)  # shape: (1,3,4)

C = A + B  # 广播 A -> (2,3,4)
print(C.shape)  # 输出 (2,3,4)


tensor([[2, 4, 6],
        [5, 7, 9]])
torch.Size([2, 3, 4])


广播失败

如果两个张量某个维度大小不匹配，且都不为 1，广播就会失败

In [32]:
a = torch.randn(2, 3)
b = torch.randn(4, 3)

print(a + b)  # 运行时报错


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0

广播机制中的增加维度其实是用unsqueeze来实现

In [34]:
a=torch.zeros(3)
b=torch.ones(1,3)
print(f"a+b= {a+b}")
a=a.unsqueeze(0)
print(f"a's shape is {a.shape}")
print(f"a+b= {a+b}")

a+b= tensor([[1., 1., 1.]])
a's shape is torch.Size([1, 3])
a+b= tensor([[1., 1., 1.]])


如果想要增加新维度（而不是合并），可以使用 torch.stack()。

In [37]:
x = torch.ones(2, 3, 4)
y = torch.zeros(2, 3, 4)

z_cat = torch.cat([x, y], dim=0)  # 形状 [4, 3, 4]
z_stack = torch.stack([x, y], dim=0)  # 形状 [2, 2, 3, 4]

print(z_cat.shape)   # torch.Size([4, 3, 4])
print(z_stack.shape) # torch.Size([2, 2, 3, 4])
print(f"z_cat is {z_cat}")
print(f"z_stack is {z_stack}")

torch.Size([4, 3, 4])
torch.Size([2, 2, 3, 4])
z_cat is tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
z_stack is tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


## 2.1.6 numpy & tensor

In [47]:
import numpy as np

In [48]:
a=np.arange(8).reshape(2,4)
a.shape

(2, 4)

代码出错的原因是 torch.tensor() 无法自动推断 NumPy 数组的数据类型，需要显式指定数据类型。

In [49]:
a=torch.tensor(a)
a

RuntimeError: Could not infer dtype of numpy.int64

In [50]:
a=torch.tensor(a,dtype=torch.int64)
a

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


| 方法                  | 适用情况            | 内存共享   | 需要手动指定 `dtype` |
| --------------------- | ------------------- | ---------- | -------------------- |
| `torch.tensor(a)`     | 适用于所有情况      | ❌ 复制数据 | 需要                 |
| `torch.from_numpy(a)` | **NumPy → PyTorch** | ✅ 共享数据 | 不需要               |

In [51]:
a=torch.from_numpy(a)
a

RuntimeError: Numpy is not available

尼玛，就逆天，估计是版本问题，草